- name: Print Used Memory
  hosts: localhost
  tasks:
    - name: Get Memory
      ansible.builtin.shell: free | grep Mem | xargs
      register: free

    - name: Set a fact
      ansible.builtin.set_fact:
        FREE: "{{ free.stdout | split(' ') }}"

    - name: set facts
      ansible.builtin.set_fact:
        total: "{{ FREE[1] }}"
        free: "{{ FREE[3] }}"

    - name: Print free output
      ansible.builtin.debug:
        msg: "{{ free|int / total|int * 100 }}"
